version: "3.3"
services:
  bitflyer-trades:
    build: .
    volumes:
      - .:/work
    command: python bitflyer_trades.py
    logging:
      driver: gcplogs
  bitmex-trades:
    build: .
    volumes:
      - .:/work
    command: python bitmex_trades.py
    logging:
      driver: gcplogs
